import type { TemplatePrintLayout } from "@workflow/contracts";

/**
 * The printed sheet's stylesheet, for the PDF renderer.
 *
 * Kept apart from the markup so the rules can be read one per line. The
 * output is one unbroken string, as Chromium receives it; the order is the
 * cascade, so a rule added later in the list wins over an earlier one of the
 * same specificity.
 */
export function documentStyles(page: TemplatePrintLayout): string {
  const pageRule = `@page{size:${page.paperSize} ${page.orientation === "LANDSCAPE" ? "landscape" : "portrait"};margin:${page.marginMm}mm}`;
  // A form whose paper packs its rows tighter than the default 10mm.
  const rowHeight = page.rowHeightMm
    ? `.grid td{height:${page.rowHeightMm}mm}.grid td,.grid th{padding-top:.6mm;padding-bottom:.6mm}`
    : "";
  const rules = [
    "*{box-sizing:border-box}",
    "html,body{margin:0;padding:0;color:#111;background:#fff;font-family:\"Noto Sans CJK TC\",\"Noto Sans TC\",\"Microsoft JhengHei\",sans-serif;font-size:10pt;line-height:1.35}",
    "body{-webkit-print-color-adjust:exact;print-color-adjust:exact}",
    ".document{position:relative;width:100%}",
    ".content{position:relative;z-index:1}",
    ".watermark{position:fixed;z-index:0;top:44%;left:50%;transform:translate(-50%,-50%) rotate(-24deg);font-size:54pt;font-weight:700;letter-spacing:.18em;color:rgba(0,0,0,.075);white-space:nowrap}",
    ".header{display:grid;grid-template-columns:1fr 2fr 1fr;align-items:end;min-height:15mm;margin-bottom:2mm}",
    ".header h1{margin:0;text-align:center;font-size:18pt;font-weight:500}",
    ".header .date{align-self:end}",
    ".header .document-code{text-align:right}",
    ".header.title-only{grid-template-columns:1fr}",
    ".header.title-only .date,.header.title-only .document-code{display:none}",
    ".header.title-left-date-right{grid-template-columns:2fr 1fr}",
    ".header.title-left-date-right h1{grid-column:1;text-align:left}",
    ".header.title-left-date-right .date{grid-column:2;grid-row:1;text-align:right}",
    ".header.title-left-date-right .document-code{display:none}",
    ".grid{width:100%;border-collapse:collapse;table-layout:fixed;break-inside:auto}",
    ".grid thead{display:table-header-group}",
    ".grid tr{break-inside:avoid}",
    ".grid th,.grid td{border:.35mm solid #222;padding:1.2mm 1.5mm;vertical-align:middle;font-weight:400}",
    ".grid th{text-align:center}",
    ".grid td{height:10mm}",
    ".grid .number{width:8mm;text-align:center;font-variant-numeric:tabular-nums}",
    ".value{min-height:5mm;white-space:pre-wrap;overflow-wrap:anywhere}",
    ".multiline{min-height:10mm}",
    ".band{margin-top:-.35mm}",
    ".caption{border:.35mm solid #222;border-bottom:0;padding:1.5mm;font-weight:500;margin-top:-.35mm}",
    ".matrix,.numbered{font-size:8.5pt}",
    ".matrix td,.matrix th,.numbered td,.numbered th{padding:1mm}",
    ".standard{text-align:center}",
    ".blanks{display:grid;border:.35mm solid #222;border-top:0}",
    ".blank{display:flex;gap:2mm;align-items:end;min-height:9mm;padding:1.2mm;border-right:.35mm solid #222;border-bottom:.35mm solid #222}",
    ".blank .value{flex:1;border-bottom:.25mm solid #222}",
    ".below-document{text-align:right;margin-top:1.5mm}",
    ".signatures{display:grid;grid-template-columns:repeat(4,auto minmax(22mm,1fr));border:.35mm solid #222;border-top:0;break-inside:avoid;min-height:18mm}",
    ".signature-label,.signature-value{padding:1.5mm;border-right:.35mm solid #222;display:flex;align-items:center;justify-content:center}",
    ".signature-label{writing-mode:horizontal-tb}",
    ".signature-value{flex-direction:column;gap:.8mm}",
    ".signature-value small{font-size:7pt}",
    ".signature-value:last-child{border-right:0}",
    ".grid.fields-wrapped{table-layout:auto}",
    // The worksheet's columns set every width; a label wraps inside its cell.
    ".grid.fields-grid{table-layout:fixed}",
    ".grid.fields-grid th{white-space:normal}",
    // A drawing beside the fields takes the room to their right.
    ".fields-grid td.fieldaside{padding:1.5mm;text-align:center;vertical-align:middle}",
    ".fields-grid td.fieldaside img{width:100%;max-height:45mm;object-fit:contain}",
    ".grid.fields-wrapped th{white-space:nowrap;width:1%}",
    ".grid.fields-wrapped td{width:33%}",
    ".diagrams{display:grid;border:.35mm solid #222;border-top:0;break-inside:avoid}",
    ".diagram{display:flex;flex-direction:column;align-items:center;gap:1.5mm;padding:2mm;border-right:.35mm solid #222}",
    ".diagram:last-child{border-right:0}",
    ".diagram-label{font-weight:500}",
    ".diagram img{max-width:100%;height:auto}",
    ".withunit{display:flex;align-items:center;gap:1mm}",
    ".withunit .value{flex:1}",
    // Several values in one box: the printed words keep their room.
    ".withunit.joined .unit{flex:none;padding:0 1mm}",
    ".unit{white-space:nowrap}",
    ".letterhead{margin-bottom:2mm}",
    ".letterhead img{width:100%;height:auto}",
    ".matrix .note{display:block;font-size:6.5pt;font-weight:400}",
    ".grid td.diagonal{background-image:linear-gradient(to top right,transparent calc(50% - .18mm),#222 calc(50% - .18mm),#222 calc(50% + .18mm),transparent calc(50% + .18mm))}",
    ".grid.fixed-rows th{padding:1.2mm .6mm;overflow-wrap:break-word}",
    ".grid td.legend{height:13mm;padding:1.5mm 2mm;text-align:right;vertical-align:bottom;white-space:pre-line}",
    ".grid td.legend.start{text-align:left;vertical-align:middle;height:18mm}",
    ".header.title-fields-right{grid-template-columns:2fr 1fr;align-items:center}",
    ".header.title-fields-right h1{grid-column:1;grid-row:1}",
    ".header.title-fields-right .date{grid-column:2;grid-row:1;display:flex;flex-direction:column;gap:1.5mm;font-size:11pt}",
    ".header.title-fields-right .document-code{display:none}",
    ".grouped td{height:7.4mm;padding:.5mm 1.2mm}",
    ".grid th.group-number{border:none;padding:0;text-align:center}",
    ".grid td.group-name{text-align:center}",
    ".group-name .value{writing-mode:vertical-rl;text-orientation:upright;margin:0 auto;font-size:14pt;letter-spacing:.25em}",
    ".grouped tbody.group+tbody.group>tr:first-child>td{border-top-width:.7mm}",
    ".grouped tbody.page-start{break-before:page}",
    ".value.choices{white-space:nowrap}",
    ".grid th.caption-row{position:relative;padding:1.5mm;font-size:13pt;font-weight:500;letter-spacing:.4em}",
    ".grid th.caption-row .caption-note{position:absolute;right:28%;bottom:1.6mm;font-size:9pt;letter-spacing:0}",
    ".grid th.corner,.reference-table th.corner{position:relative;height:10mm;background-image:linear-gradient(to top right,transparent calc(50% - .18mm),#222 calc(50% - .18mm),#222 calc(50% + .18mm),transparent calc(50% + .18mm))}",
    "th.corner .across{position:absolute;top:.6mm;right:1mm;font-size:8pt}",
    "th.corner .down{position:absolute;bottom:.6mm;left:1mm;font-size:8pt}",
    ".reference{display:flex;gap:4mm;align-items:center;justify-content:space-between;border:.35mm solid #222;margin-top:-.35mm;padding:3mm;break-inside:avoid}",
    ".reference-drawing{flex:1.3;min-width:0}",
    ".reference-drawing img{width:100%;height:auto}",
    ".reference-table{flex:1;border-collapse:collapse;font-size:8.5pt}",
    ".reference-table th,.reference-table td{border:.25mm solid #222;padding:.6mm 1.2mm;font-weight:400;text-align:left}",
    ".reference-table thead th{text-align:center}",
    ".reference-table thead th small{display:block;font-size:8pt}",
    ".reference-table th.corner{min-width:18mm}",
    ".grid th{white-space:pre-line}",
    ".grid tr.joined th:not(.corner){border-bottom-style:hidden}",
    ".grid tr.standard.joined td{border-top-style:hidden}",
    ".grid tr.standard td{height:8mm}",
    ".grid td.block-gap{border-top-style:hidden;border-bottom-style:hidden;background:#fff;padding:0}",
    ".blocks .withunit .unit{margin-left:auto}",
    ".withunit .unit:first-child{order:0}",
    ".header-line{margin-bottom:1mm;font-size:11pt}",
    ".header-line.center{text-align:center;font-size:14pt}",
    ".header-line.end{text-align:right}",
    ".below-document{display:flex;justify-content:space-between}",
    ".reference-drawing img{max-height:32mm;object-fit:contain}",
    ".grid.fields-wrapped th{white-space:pre}",
    ".grid.fields-wrapped td{min-width:14mm}",
    ".below-document>span:last-child{margin-left:auto}",
    rowHeight,
    ".grid .spacer{border-top:hidden;border-bottom:hidden;border-left:.35mm solid #222;border-right:.35mm solid #222;background:#fff;padding:0}",
    // A heading the paper sets smaller to fit its column: 12pt beside 14pt.
    ".grid th.small{font-size:8.5pt;padding-left:.8mm;padding-right:.8mm}",
    // One printed cell holding several values: `E: ＿K* ＿箱` side by side,
    // `E: ＿K` over `I: ＿K`.
    ".grid td.shared .part{display:flex;align-items:center;gap:.8mm}",
    ".grid td.shared.inline .part{display:inline-flex;width:50%;vertical-align:middle}",
    ".grid td.shared{padding:.6mm .8mm}",
    ".grid td.shared .part .value{flex:1;min-width:3mm;white-space:nowrap;overflow-wrap:normal}",
    ".grid td.shared.stacked .part+.part{margin-top:1mm}",
    // The back of the sheet: a portrait page of its own, as the paper's back.
    "@page back{size:A4 portrait}",
    ".back-side{page:back;break-before:page}",
    ".blanks.back{border:0;gap:0 6mm}",
    ".blanks.back .blank{min-height:44mm;align-items:flex-start;padding:1.5mm 0;font-size:16pt;border-right:0!important;border-bottom:1mm solid #222!important}",
    ".blanks.back .blank .value{border-bottom:0;font-size:10pt;align-self:center}",
    // The printed matrix of 首件/巡迴檢驗單: its label down the left, headings
    // written in as `＿日 ＿時 ＿分`, a ✓/✗ mark, the drawing beside the rows.
    ".matrix.printed{font-size:9pt}",
    // 公差, printed in every row beside a written 標準.
    ".matrix.printed td.printed{text-align:center;white-space:nowrap}",
    ".matrix.printed td,.matrix.printed th{padding:.4mm .8mm}",
    ".matrix.printed th.side-label{writing-mode:vertical-rl;text-orientation:upright;letter-spacing:.6em;font-size:11pt}",
    ".matrix.printed th.entry{text-align:right;white-space:nowrap}",
    ".matrix.printed .entry-part{display:inline-flex;align-items:baseline;gap:.4mm;margin-left:1.5mm}",
    ".matrix.printed .entry-part .value{min-width:3mm;text-align:right}",
    ".matrix.printed .value.mark{text-align:center;font-size:11pt}",
    // The drawing fills its cell without setting the height of the rows it runs down.
    ".matrix.printed td.aside{position:relative;padding:0}",
    ".matrix.printed .aside-fill{position:absolute;inset:0;padding:1.5mm;display:flex;flex-direction:column}",
    ".matrix.printed .aside-choice{margin-bottom:1mm}",
    ".matrix.printed td.aside img{display:block;flex:1;min-height:0;width:100%;object-fit:contain}",
    ".matrix.printed .aside-note{margin:1mm 0 0 auto;width:62%;border:.25mm solid #222;padding:1mm;font-weight:700}",
    ".reference-entry{flex:1;align-self:stretch;min-width:0}",
    // 首件/巡迴檢驗單 fits its whole page only with the 公差 table set close.
    ".reference.with-entry{padding:1.5mm 3mm;align-items:stretch}",
    ".reference.with-entry .reference-table td,.reference.with-entry .reference-table th{padding:.2mm 1.2mm}",
    ".reference-entry-label{margin-bottom:1mm}",
    ".bottom-lines{display:flex;justify-content:space-between;margin-top:1mm}",
  ];
  return `${pageRule}\n${rules.join("")}`;
}
